version: '3.8'

services:
  service-notifications:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '50061:50061'
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50061
      - WS_PORT=3001
      - WS_CORS_ORIGIN=http://localhost:6000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=notifications_db
    depends_on:
      - postgres
    networks:
      - crm-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifications_db
    volumes:
      - notifications_db_data:/var/lib/postgresql/data
    networks:
      - crm-network

networks:
  crm-network:
    external: true

volumes:
  notifications_db_data:
